// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: scrumbler.proto

package scrumbler_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ScrumblerV1_Scrumbler_FullMethodName = "/scrumbler_v1.ScrumblerV1/Scrumbler"
)

// ScrumblerV1Client is the client API for ScrumblerV1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ScrumblerV1Client interface {
	Scrumbler(ctx context.Context, in *ScrumblerRequest, opts ...grpc.CallOption) (*ScrumblerResponse, error)
}

type scrumblerV1Client struct {
	cc grpc.ClientConnInterface
}

func NewScrumblerV1Client(cc grpc.ClientConnInterface) ScrumblerV1Client {
	return &scrumblerV1Client{cc}
}

func (c *scrumblerV1Client) Scrumbler(ctx context.Context, in *ScrumblerRequest, opts ...grpc.CallOption) (*ScrumblerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScrumblerResponse)
	err := c.cc.Invoke(ctx, ScrumblerV1_Scrumbler_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScrumblerV1Server is the server API for ScrumblerV1 service.
// All implementations must embed UnimplementedScrumblerV1Server
// for forward compatibility.
type ScrumblerV1Server interface {
	Scrumbler(context.Context, *ScrumblerRequest) (*ScrumblerResponse, error)
	mustEmbedUnimplementedScrumblerV1Server()
}

// UnimplementedScrumblerV1Server must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScrumblerV1Server struct{}

func (UnimplementedScrumblerV1Server) Scrumbler(context.Context, *ScrumblerRequest) (*ScrumblerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Scrumbler not implemented")
}
func (UnimplementedScrumblerV1Server) mustEmbedUnimplementedScrumblerV1Server() {}
func (UnimplementedScrumblerV1Server) testEmbeddedByValue()                     {}

// UnsafeScrumblerV1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScrumblerV1Server will
// result in compilation errors.
type UnsafeScrumblerV1Server interface {
	mustEmbedUnimplementedScrumblerV1Server()
}

func RegisterScrumblerV1Server(s grpc.ServiceRegistrar, srv ScrumblerV1Server) {
	// If the following call pancis, it indicates UnimplementedScrumblerV1Server was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ScrumblerV1_ServiceDesc, srv)
}

func _ScrumblerV1_Scrumbler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScrumblerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScrumblerV1Server).Scrumbler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScrumblerV1_Scrumbler_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScrumblerV1Server).Scrumbler(ctx, req.(*ScrumblerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ScrumblerV1_ServiceDesc is the grpc.ServiceDesc for ScrumblerV1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScrumblerV1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scrumbler_v1.ScrumblerV1",
	HandlerType: (*ScrumblerV1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Scrumbler",
			Handler:    _ScrumblerV1_Scrumbler_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scrumbler.proto",
}
