name: CI/CD
on:
  push:
    branches: [ "main", "staging", "development" ]
  pull_request:
    branches: [ "main", "staging", "development" ]
env:
  CONTAINER_NAME: "${{ github.event.repository.name }}-${{ github.ref_name == 'main' && 'production' || github.ref_name }}"
  IMAGE_NAME: "${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}-${{ github.ref_name == 'main' && 'production' || github.ref_name }}:${{ github.sha }}"
jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'production' || github.ref_name }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Make .env
        run: echo "${{ secrets.ENV_FILE }}" > .env
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'production' || github.ref_name }}
    needs: build
    steps:
      -
        name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            docker stop ${{ env.CONTAINER_NAME }}
            docker rm ${{ env.CONTAINER_NAME }}
            docker run -d -p ${{ vars.SERVER_PORT }}:${{ vars.SERVER_PORT }} --name ${{ env.CONTAINER_NAME }} -t ${{ env.IMAGE_NAME }}
